# ADP@0.971 => https://wandb.ai/tristan_research/framework_tuning_amalgame_linear/sweeps/o240hcm8?nw=nwusertristanbilot

featurization:
  embed_nodes:
    emb_dim: 64
    seed: 5

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 256
