# ADP@0.501 => https://wandb.ai/tristan_research/framework_tuning_threatrace/sweeps/4ixj6w3p?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.3
