# ADP@0.0.785=> https://wandb.ai/tristan_research/framework_tuning_velox/sweeps/imsjkbnc/table?nw=nwusertristanbilot

featurization:
  feat_training:
    emb_dim: 256

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 64
