# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_nodlink/runs/vu1gquu0/overview

preprocessing:
  transformation:
    used_methods: undirected

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 64
    node_hid_dim: 64
    encoder:
      dropout: 0.3
