# ADP@0.5 => https://wandb.ai/tristan_research/framework_tuning_kairos/sweeps/ln28gkpj/workspace?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 15.0

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 64
    node_out_dim: 64
    encoder:
      dropout: 0.3
