# ADP@0.5 => https://wandb.ai/tristan_research/tuning_amalgame_linear/sweeps/k47b3hhk?nw=nwusertristanbilot&panelDisplayName=adp_score

featurization:
  embed_nodes:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 256
