services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-create-empty-databases.sh:/docker-entrypoint-initdb.d/init-create-empty-databases.sh # executed when container created
      - ./settings/scripts:/scripts
      - ${INPUT_DIR}:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pids:
    build: ./image
    container_name: pids
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=8888
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./:/home
      - ${ARTIFACTS_DIR}:/home/artifacts
    entrypoint: bash
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data: