# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_nodlink/sweeps/tnil0464?nw=nwusertristanbilot

preprocessing:
  transformation:
    used_methods: undirected

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
    node_hid_dim: 128
    encoder:
      dropout: 0.3
  