# ADP@0.009 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/vecdxw04/workspace

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 64
    node_out_dim: 64
    encoder:
      dropout: 0.3
