# ADP@0.25 => https://wandb.ai/tristan_research/framework_tuning_threatrace/sweeps/44m1sy9o?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.3
