# ADP@0.5 => https://wandb.ai/tristan_research/tuning_amalgame_linear3/sweeps/kkour0ox?nw=nwusertristanbilot

featurization:
  embed_nodes:
    emb_dim: 256

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 64
