# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_amalgame_linear_hfh/runs/v3vlgpto?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 1.0

featurization:
  embed_nodes:
    emb_dim: 64
    seed: 42

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 256
    node_out_dim: 128
    encoder:
      dropout: 0.1
