# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_velox_hfh/runs/v3vlgpto?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 1.0

featurization:
  feat_training:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 64
