# ADP@0.334 => https://wandb.ai/tristan_research/framework_tuning_kairos/sweeps/89vf6ut8/workspace

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.3
