preprocessing:
  build_graphs:
    time_window_size: 1.0

featurization:
  embed_nodes:
    epochs: 20

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    node_hid_dim: 128
    encoder:
      dropout: 0.2
  