# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_orthrus/sweeps/7t3iyuyy?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 1.0

detection:
  gnn_training:
    encoder:
      dropout: 0.1
  