# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_nodlink/sweeps/z6vbbla2?nw=nwusertristanbilot
# In table: https://wandb.ai/tristan_research/framework_tuning_nodlink/runs/n6qfrltm/overview

preprocessing:
  build_graphs:
    time_window_size: 1.0
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    epochs: 20

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    node_hid_dim: 128
    encoder:
      dropout: 0.2
  