# Simply the same config as amalgame_orthrus + encoder set to none

preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: False
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    emb_dim: 128
    epochs: 50
    training_split: train
    used_method: feature_word2vec
    use_seed: True
    temporal_rw:
      walk_length: 30
      num_walks: 10
      trw_workers: 8
      time_weight: uniform
      half_life: 1
      window_size: 5
      min_count: 1
      use_skip_gram: True
      wv_workers: 6
      compute_loss: True
      negative: 5
      decline_rate: 30
    doc2vec:
      include_neighbors: False
      alpha: 0.025
    word2vec:
      walk_length: 30
      num_walks: 10
      context_window_size: 5
      min_count: 0
      use_skip_gram: True
      num_workers: 15
      compute_loss: True
      add_paths: False
    feature_word2vec:
      alpha: 0.025
      window_size: 5
      min_count: 1
      use_skip_gram: True
      num_workers: 15
      compute_loss: True
      negative: 5
      decline_rate: 30
    fasttext:
      min_count: 2
      alpha: 0.01
      window_size: 3
      negative: 3
      num_workers: 15
      use_pretrained_fb_model: False
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 3
    patience: 3
    lr: 0.0001
    weight_decay: 0.00001
    node_hid_dim: 128
    node_out_dim: 128
    inference_device: cuda
    grad_accumulation: 1
    encoder:
      node_features: node_emb,node_type
      neighbor_sampling: []
      edge_features: edge_type
      dropout: 0.3
      used_methods: graph_attention
      custom:
        architecture_str: linear(1.0) | relu | linear(0.5)
      graph_attention:
        activation: relu
        num_heads: 8
        concat: True
      tgn:
        tgn_batch_size: 1024
        tgn_batch_size_inference: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        tgn_neighbor_n_hop: 1
        use_node_feats_in_gnn: True
        use_memory: False
        use_time_order_encoding: False
      sage:
        activation: relu
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        balanced_loss: False
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(0.5) | relu
          # architecture_str: none
          src_dst_projection_coef: 2
      reconstruct_node_features:
        loss: MSE
        decoder: nodlink
        custom_mlp:
          architecture_str: linear(0.5) | relu
      predict_node_type:
        decoder: custom_mlp
        custom_mlp:
          architecture_str: linear(0.5) | relu
        balanced_loss: False
      
      use_few_shot: True
      few_shot:
        attack_generation_method: synthetic_attack_naive
        synthetic_attack_naive:
          num_attacks: 1
          num_malicious_process: 5
          num_unauthorized_file_access: 20
          process_selection_method: random # TODO: try new methods
        
        include_attacks_in_ssl_training: False
        freeze_encoder: True
        num_epochs_few_shot: 50
        patience_few_shot: 5
        lr_few_shot: 0.001
        weight_decay_few_shot: 0.00001
        decoder:
          used_methods: detect_edge_few_shot
          detect_edge_few_shot:
            decoder: edge_mlp # custom_mlp
            custom_mlp:
              architecture_str: linear(1.0) | relu
            edge_mlp:
              architecture_str: linear(0.5) | relu
              src_dst_projection_coef: 1

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: False
