preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: False
    node_label_features:
      subject: path, cmd_line
      file: path
      netflow: remote_ip, remote_port
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    emb_dim: 30
    epochs: 10 # 300
    training_split: train
    used_method: flash
    use_seed: True
    flash:
      min_count: 1
      workers: 8
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 22
    lr: 0.01
    weight_decay: 0.0005
    node_hid_dim: 30
    node_out_dim: 3
    encoder:
      node_features: node_emb
      neighbor_sampling: [-1, -1]
      edge_features: none
      used_methods: sage
      sage:
        dropout: 0.5
        activation: relu
    decoder:
      used_methods: predict_node_type
      predict_node_type:
        decoder: none
        balanced_loss: True

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: node_evaluation
    node_evaluation:
      threshold_method: flash
      use_dst_node_loss: True
