preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 128
    used_method: flash
    use_seed: True
    flash:
      vector_size: 30
      window: 5
      min_count: 1
      workers: 8
      epochs: 300
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: flash
    use_seed: True
    num_epochs: 6
    lr: 0.00001
    weight_decay: 0.00001
    node_hid_dim: 128
    node_out_dim: 64
    node_level: False
    flash:
      in_channel: 30
      out_channel: 3
      lr: 0.01
      weight_decay: 0.0005
      epochs: 22

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: flash_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
