preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    mimicry_edge_num: 0
    time_window_size: 15.0
    use_hashed_label: False
    fuse_edge: True
    node_label_features:
      subject: path
      file: path
      netflow: remote_ip, remote_port
    multi_dataset: none
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    emb_dim: 16
    training_split: all
    used_method: hierarchical_hashing
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 12
    patience: 3
    lr: 0.00005
    weight_decay: 0.01
    node_hid_dim: 100
    node_out_dim: 100
    inference_device: cuda
    grad_accumulation: 1
    fix_buggy_graph_reindexer: False
    encoder:
      node_features: node_emb,node_type
      neighbor_sampling: []
      edge_features: msg,time_encoding
      dropout: 0.0
      used_methods: graph_attention,tgn
      graph_attention:
        activation: relu
        num_heads: 4
        concat: True
      tgn:
        tgn_batch_size: 1024
        tgn_batch_size_inference: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        tgn_neighbor_n_hop: 1
        use_node_feats_in_gnn: False
        use_memory: True
        use_time_order_encoding: False
        fix_buggy_orthrus_TGN: False
        project_src_dst: True
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        balanced_loss: False
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(2) | dropout(0.5) | tanh | linear(0.25) | dropout(0.25) | tanh | linear(0.25) | dropout(0.5) | tanh
          src_dst_projection_coef: 2

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: False
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True
