preprocessing:
  build_graphs:
    time_window_size: 15

featurization:
  build_random_walks:
    walk_length: 30
    num_walks: 10
  embed_nodes:
    epochs: 5 
    emb_dim: 128
    context_window_size: 5
    min_count: 0
    use_skip_gram: True
    num_workers: 6
    compute_loss: True
    add_paths: False
  embed_edges:
    include_edge_type: True

detection:
  gnn_training:
    num_epochs: 50
    lr: 0.000001
    weight_decay: 0.01
    node_hid_dim: 64
    node_out_dim: 64
    tgn_batch_size: 1024
    tgn_node_state_dim: 100
    tgn_time_dim: 100
    tgn_neighbor_size: 20
  gnn_testing:
    threshold_method: str
  node_evaluation:
    threshold_method: supervised_best_threshold
    use_dst_node_loss: False
    use_loss_sum: False
