preprocessing:
  build_graphs:
    time_window_size: 15
    use_hashed_label: False
    node_label_features:
      subject: path
      file: path
      netflow: remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 128
    used_method: hierarchical_hashing
  embed_edges:
    include_edge_type: True

detection:
  gnn_training:
    use_seed: False
    num_epochs: 50
    lr: 0.00005
    weight_decay: 0.01
    node_hid_dim: 100
    node_out_dim: 100
    node_dropout: 0.0
    encoder:
      use_node_type_in_node_feats: True
      neighbor_sampling: []
      used_methods: graph_attention,tgn
      graph_attention:
        num_heads: 8
      tgn:
        tgn_batch_size: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        use_time_encoding: True
        use_msg_as_edge_feature: True
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        used_method: kairos

  gnn_testing:
    threshold_method: str
  evaluation:
    used_method: queue_evaluation
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True
