preprocessing:
  build_graphs:
    time_window_size: 15
    use_hashed_label: False
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 128
    used_method: doc2vec
    doc2vec:
      epochs: 100
      alpha: 0.025
      min_alpha: 0.00025
    word2vec:
      walk_length: 30
      num_walks: 10
      epochs: 5 
      context_window_size: 5
      min_count: 0
      use_skip_gram: True
      num_workers: 6
      compute_loss: True
      add_paths: False
  embed_edges:
    include_edge_type: True

detection:
  gnn_training:
    use_seed: False
    num_epochs: 50
    lr: 0.000001
    weight_decay: 0.01
    node_hid_dim: 64
    node_out_dim: 64
    node_dropout: 0.0
    encoder:
      use_node_type_in_node_feats: False
      used_methods: graph_attention,tgn
      graph_attention:
        num_layers: 2
      tgn:
        tgn_batch_size: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        use_time_encoding: False
        use_msg_as_edge_feature: False
    decoder:
      used_methods: node_recon_MLP
      node_recon_MLP:
        loss: SCE
        recon_hid_dim: 100
        recon_use_bias: True
  gnn_testing:
    threshold_method: str
  evaluation:
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_mean_node_loss: False 
    queue_evaluation:
      queue_arg: max_val_loss
