preprocessing:
  build_graphs:
    time_window_size: 15

featurization:
  build_random_walks:
    walk_length: 30
    num_walks: 10
  embed_nodes:
    epochs: 5 
    emb_dim: 128
    context_window_size: 5
    min_count: 0
    use_skip_gram: True
    num_workers: 6
    compute_loss: False
    add_paths: False
