preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: False
    node_label_features:
      subject: path
      file: path
      netflow: remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 16
    used_method: hierarchical_hashing
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 6
    lr: 0.00005
    weight_decay: 0.01
    node_hid_dim: 100
    node_out_dim: 100
    encoder:
      use_node_type_in_node_feats: True
      neighbor_sampling: []
      edge_features: msg,time_encoding
      used_methods: graph_attention,tgn
      graph_attention:
        dropout: 0.0
        activation: relu
        num_heads: 8
      tgn:
        tgn_batch_size: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        use_node_feats_in_gnn: False
        use_memory: True
        use_time_order_encoding: False
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        used_method: kairos

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 30
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True
