preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: path, cmd_line
      file: path
      netflow: remote_ip
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    used_method: only_type
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 10
    lr: 0.001
    weight_decay: 0.0005
    node_in_dim: 3
    node_hid_dim: 64
    node_out_dim: 3
    encoder:
      node_features: node_type
      neighbor_sampling: []
      edge_features: edge_type
      used_methods: magic_gat
      magic_gat:
        num_layers: 3
        num_heads: 4
        negative_slope: 0.2
        alpha_l: 3.0
        optimizer: adam
        activation: prelu
    decoder:
      balanced_loss: False
      used_methods: reconstruct_masked_features,reconstruct_masked_struct
      reconstruct_masked_features:
        decoder: magic_gat
        mask_rate: 0.5
        loss: SCE
        num_layers: 3
        num_heads: 4
        negative_slope: 0.2
        encoder_to_decoder: 16,64
      reconstruct_masked_struct:
        decoder: struct_mlp
        loss: BCE
        negative_slope: 0.2
        input_dim: 16
        hidden_dim: 64

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: node_evaluation
    node_evaluation:
      threshold_method: magic
      use_dst_node_loss: True
