preprocessing:
  build_graphs:
    used_method: magic
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: path, cmd_line
      file: path
      netflow: remote_ip
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    emb_dim: 128
    training_split: all
    used_method: magic
    use_seed: True
  embed_edges:
    to_remove: True
    magic:
      num_hidden: 64
      max_epoch: 10
      num_layers: 3
      negative_slope: 0.2
      mask_rate: 0.5
      alpha_l: 3.0
      optimizer: adam
      lr: 0.001
      weight_decay: 0.0005

detection:
  gnn_training:
    used_method: magic

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    used_method: magic_node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
