_include_yml: orthrus_non_snooped

detection:
  gnn_training:
    fix_buggy_graph_reindexer: True
    encoder:
      tgn:
        fix_buggy_orthrus_TGN: True

  evaluation:
    used_method: edge_evaluation
