_include_yml: orthrus_fixed

featurization:
  embed_nodes:
    used_method: only_type

detection:
  graph_preprocessing:
    fix_buggy_graph_reindexer: True
    global_batching:
      used_method: unique_edge_types
    intra_graph_batching:
      used_methods: tgn_last_neighbor
      tgn_last_neighbor:
        fix_tgn_neighbor_loader: False
        fix_buggy_orthrus_TGN: True
    inter_graph_batching:
      used_method: graph_batching
      inter_graph_batch_size: 1024

  gnn_training:
    lr: 0.001

  evaluation:
    used_method: edge_evaluation
    best_model_selection: best_discrimination
