# Simply Orthrus' config, without test data during training text embeddings + without clustering after thresholding
# to avoid data snooping. This config is thus orthrus without the "cheating" techniques for fair comparison.

_include_yml: orthrus

featurization:
  feat_training:
    training_split: train
   
detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    encoder:
      dropout: 0.3
     
  evaluation:
    node_evaluation:
      use_kmeans: False
