preprocessing:
  build_graphs:
    time_window_size: 15
    use_hashed_label: False
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 128
    used_method: word2vec
    doc2vec:
      epochs: 100
      alpha: 0.025
      min_alpha: 0.00025
    word2vec:
      walk_length: 30
      num_walks: 10
      epochs: 5 
      context_window_size: 5
      min_count: 0
      use_skip_gram: True
      num_workers: 6
      compute_loss: True
      add_paths: False
  embed_edges:
    include_edge_type: True

detection:
  gnn_training:
    use_seed: False
    num_epochs: 50
    lr: 0.0001
    weight_decay: 0.001
    node_hid_dim: 64
    node_out_dim: 64
    node_dropout: 0.0
    encoder:
      use_node_type_in_node_feats: True
      used_methods: graph_attention
      graph_attention:
        num_heads: 8
      tgn:
        tgn_batch_size: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        use_time_encoding: True
        use_msg_as_edge_feature: True
    decoder:
      used_methods: predict_edge_contrastive, reconstruct_node
      predict_edge_type:
        used_method: custom
        custom:
          dropout: 0.5
          num_layers: 2
          activation: relu
      predict_edge_contrastive:
        used_method: linear
        inner_product:
          dropout: 0.0
        linear:
          dropout: 0.0
      reconstruct_node:
        loss: SCE
        recon_hid_dim: 100
        recon_use_bias: True

  gnn_testing:
    threshold_method: str
  evaluation:
    used_method: queue_evaluation
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True
