preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: type, path
      file: type, path
      netflow: type, remote_ip, remote_port
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    used_method: provd
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: provd
    use_seed: True
    num_epochs: 6
    lr: 0.00001
    weight_decay: 0.00001
    node_hid_dim: 128
    node_out_dim: 64
    encoder:
      node_features: node_emb,node_type
      neighbor_sampling: []
      edge_features: edge_type
      used_methods: tgn,graph_attention
      graph_attention:
        dropout: 0.5
        activation: relu
        num_heads: 8
      tgn:
        tgn_batch_size: 1024
        tgn_memory_dim: 100
        tgn_time_dim: 100
        tgn_neighbor_size: 20
        use_node_feats_in_gnn: True
        use_memory: False
        use_time_order_encoding: False
      sage:
        dropout: 0.0
        activation: relu
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(0.5) | relu
      # predict_edge_contrastive:
      #   neg_sampling_method: previously_seen_nodes
      #   used_method: linear
      #   inner_product:
      #     dropout: 0.0
      #   linear:
      #     dropout: 0.0

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 20
    node_tw_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 3
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True
