preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: False
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    epochs: 1
    emb_dim: 16
    training_split: all
    used_method: feature_word2vec
    use_seed: True
    temporal_rw:
      walk_length: 30
      num_walks: 10
      trw_workers: 8
      time_weight: uniform
      half_life: 1
      window_size: 5
      min_count: 1
      use_skip_gram: True
      wv_workers: 6
      compute_loss: True
      negative: 5
      decline_rate: 30
    doc2vec:
      include_neighbors: False
      alpha: 0.025
    word2vec:
      walk_length: 30
      num_walks: 10
      context_window_size: 5
      min_count: 0
      use_skip_gram: True
      num_workers: 15
      compute_loss: True
      add_paths: False
    feature_word2vec:
      window_size: 5
      min_count: 1
      use_skip_gram: True
      num_workers: 15
      compute_loss: True
      negative: 5
      decline_rate: 30
    flash:
      min_count: 1
      workers: 8
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 1
    patience: 3
    lr: 0.00001
    weight_decay: 0.00001
    node_hid_dim: 16
    node_out_dim: 16
    inference_device: cuda
    grad_accumulation: 1
    encoder:
      node_features: node_emb,node_type
      neighbor_sampling: []
      edge_features: edge_type
      dropout: 0.5
      used_methods: tgn,graph_attention
      graph_attention:
        activation: relu
        num_heads: 8
        concat: True
      tgn:
        tgn_batch_size: 1024
        tgn_batch_size_inference: 1024
        tgn_memory_dim: 16
        tgn_time_dim: 16
        tgn_neighbor_size: 20
        tgn_neighbor_n_hop: 1
        use_node_feats_in_gnn: True
        use_memory: False
        use_time_order_encoding: False
        use_buggy_orthrus_TGN: True
      sage:
        activation: relu
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(0.5) | relu
      reconstruct_node_features:
        loss: MSE
        decoder: none
      reconstruct_edge_embeddings:
        loss: MSE
        decoder: none
      reconstruct_node_embeddings:
        loss: MSE
        decoder: none
      predict_edge_type:
        balanced_loss: False
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(0.5)
      predict_node_type:
        balanced_loss: False
        decoder: edge_mlp
        edge_mlp:
          architecture_str: linear(0.5)
      # predict_edge_contrastive:
      #   neg_sampling_method: previously_seen_nodes
      #   used_method: linear
      #   inner_product:
      #     dropout: 0.0
      #   linear:
      #     dropout: 0.0

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 20
    node_tw_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 3
    queue_evaluation:
      queue_threshold: 20
      used_method: kairos_idf_queue
      kairos_idf_queue:
        include_test_set_in_IDF: True

triage :
  tracing:
    used_method: depimpact
    depimpact:
      used_method: component
      score_method: degree
      workers: 8
      visualize: False
