preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    mimicry_edge_num: 0
    time_window_size: 15.0
    use_hashed_label: False
    fuse_edge: True
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port
    multi_dataset: none
  transformation:
    used_methods: none

featurization:
  feat_training:
    used_method: only_type
  feat_inference:
    to_remove: True

detection:
  graph_preprocessing:
    save_on_disk: False
    node_features: node_type,edges_distribution
    edge_features: none
    fix_buggy_graph_reindexer: False
    global_batching:
      used_method: none
    intra_graph_batching:
      used_methods: none
    inter_graph_batching:
      used_method: none
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 12
    patience: 3
    lr: 0.01
    weight_decay: 0.0005
    node_hid_dim: 32
    node_out_dim: 3
    grad_accumulation: 1
    encoder:
      dropout: 0.5
      used_methods: sage
      sage:
        activation: relu
        num_layers: 2
    decoder:
      used_methods: predict_node_type
      predict_node_type:
        decoder: none
        balanced_loss: False

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    best_model_selection: best_adp
    used_method: node_evaluation
    node_evaluation:
      threshold_method: threatrace
      use_kmeans: False
