preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port

featurization:
  embed_nodes:
    used_method: only_type
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 30
    lr: 0.01
    weight_decay: 0.0005
    node_hid_dim: 32
    node_out_dim: 3
    encoder:
      node_features: node_type,edges_distribution
      neighbor_sampling: [-1, -1]
      edge_features: edge_type
      used_methods: sage
      sage:
        dropout: 0.5
        activation: relu
    decoder:
      used_methods: predict_node_type

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa_v4
    used_method: node_evaluation
    node_evaluation:
      threshold_method: threatrace
