preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    mimicry_edge_num: 0
    time_window_size: 15.0
    use_hashed_label: False
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    used_method: only_type
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 12
    patience: 3
    lr: 0.01
    weight_decay: 0.0005
    node_hid_dim: 32
    node_out_dim: 3
    inference_device: cuda
    grad_accumulation: 1
    # edge_batch_size: 1024
    encoder:
      node_features: node_type,edges_distribution
      neighbor_sampling: [-1, -1]
      edge_features: none
      dropout: 0.5
      used_methods: sage
      sage:
        activation: relu
    decoder:
      used_methods: predict_node_type
      predict_node_type:
        decoder: none
        balanced_loss: False

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    used_method: node_evaluation
    node_evaluation:
      threshold_method: threatrace
      use_kmeans: False
