# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_orthrus/runs/gaiu0hjs?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 3.0

detection:
  gnn_training:
    lr: 0.0005
    node_hid_dim: 256
    node_out_dim: 320
    encoder:
      dropout: 0.5
