# ADP@0.35 => https://wandb.ai/tristan_research/framework_tuning_threatrace/sweeps/74jk4jda/workspace
# in table: ADP@0.178 => https://wandb.ai/tristan_research/framework_tuning_threatrace/sweeps/kk7yvv5h/workspace?nw=nwusertristanbilot

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 64
    encoder:
      dropout: 0.4
