# ADP@0.348 => https://wandb.ai/tristan_research/framework_tuning_magic/sweeps/c9n4j05i?nw=nwusertristanbilot
# in table: ADP@0.346 => https://wandb.ai/tristan_research/framework_tuning_magic/sweeps/6sq493td/workspace

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.4