preprocessing:
  transformation:
    used_methods: none

featurization:
  feat_training:
    epochs: 20

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 256
    node_hid_dim: 256
    encoder:
      dropout: 0.2
  