# ADP@0.709 => https://wandb.ai/tristan_research/framework_tuning_rcaid/runs/iyu89o4g/overview

featurization:
  embed_nodes:
    emb_dim: 32

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    encoder:
      dropout: 0.2
