preprocessing:
  build_graphs:
    time_window_size: 5.0

featurization:
  feat_training:
    emb_dim: 64

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 64
    encoder:
      dropout: 0.3