# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_velox/sweeps/kpf4d2l1/table?nw=nwusertristanbilot

featurization:
  feat_training:
    emb_dim: 64

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
    encoder:
      dropout: 0.3