preprocessing:
  build_graphs:
    time_window_size: 5.0

featurization:
  feat_training:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    encoder:
      dropout: 0.3
