# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_kairos/sweeps/0v8aubgs?nw=nwusertristanbilot

featurization:
  feat_training:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
    encoder:
      dropout: 0.3