# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_magic/sweeps/a4knwbuo?nw=nwusertristanbilot

featurization:
  embed_nodes:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
