# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/s2o9pclx/table

preprocessing:
  build_graphs:
    time_window_size: 5.0

featurization:
  embed_nodes:
    emb_dim: 64

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 64
    encoder:
      dropout: 0.3