# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_velox/sweeps/9u13aiac?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 0.5

featurization:
  embed_nodes:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
    encoder:
      dropout: 0.3
