#ADP@0.333 => https://wandb.ai/tristan_research/framework_tuning_orthrus/sweeps/h51548rx/table?nw=nwuserbaoxiang

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 128
    # node_out_dim: -1
    encoder:
      dropout: 0.3