#ADP@1 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/23pr447v/table?nw=nwuserbaoxiang

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 128
    encoder:
      dropout: 0.3