#ADP@1 => https://wandb.ai/tristan_research/framework_tuning_magic/sweeps/314t3q26/table?nw=nwuserbaoxiang

preprocessing:
  build_graphs:
    time_window_size: 15.0

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    # node_out_dim: -1
    encoder:
      dropout: 0.3