# https://wandb.ai/tristan_research/tuning_nodlink/runs/1jk0yvtv/overview
featurization:
  embed_nodes:
    epochs: 10

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    node_hid_dim: 256
  