# https://wandb.ai/tristan_research/tuning_nodlink/sweeps/ekbjc8g5/workspace?nw=nwusertristanbilot
featurization:
  embed_nodes:
    epochs: 20

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    node_hid_dim: 128
    encoder:
      dropout: 0.2
  