# https://wandb.ai/tristan_research/tuning_kairos/runs/o8cm07r3?nw=nwusertristanbilot
featurization:
  embed_nodes:
    emb_dim: 32

detection:
  gnn_training:
    lr: 0.00005
    node_hid_dim: 200
    node_out_dim: 100
