# ADP@0.15 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/gz2091zk/workspace

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 128
    encoder:
      dropout: 0.3
  