featurization:
  feat_training:
    epochs: 10
    emb_dim: 128
    training_split: train
    used_method: word2vec
    word2vec:
      alpha: 0.025
      window_size: 5
      min_count: 1
      use_skip_gram: True
      num_workers: 15
      compute_loss: True
      negative: 5
      decline_rate: 30
