# Site name
site_name: PIDSMaker Documentation
# site_url: https:// # TODO
repo_url: https://github.com/ubc-provenance/PIDSMaker

# Navigation menu
nav:
  - Home: index.md
  - Install: ten-minute-install.md
  - Introduction: introduction.md
  - Pipeline: pipeline.md
  - Tutorial: tutorial.md
  - Configuration:
    - Featurization: config/featurization.md
    - Encoders: config/encoders.md
    - Decoders: config/decoders.md
    - Objectives: config/objectives.md
    - Tasks: config/tasks.md
  - Features:
    - Hyperparameter Tuning: features/tuning.md
    - Batching and Sampling: features/batching.md
    - Instability Measurement: features/instability.md
  - Development: dev.md
  - Contribute:
    - Guidelines: contribute/guidelines.md
  - Release notes: release_notes.md
  
# Theme
theme:
    features:
      - tabs
      - content.code.copy
      - content.code.annotate
      - navigation.instant
      # - navigation.expand
      - navigation.sections
    name: material
    icon:
      logo: material/book-open-page-variant-outline
    favicon: assets/logo.ico
    static_templates:
      - 404.html
    palette:
      scheme: default
      primary: indigo

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path: .
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ubc-provenance/PIDSMaker

extra_css:
  - extra.css

copyright: Copyright &copy; 2025 UBC provenance team
