# Site name
site_name: PIDSMaker Documentation

# Navigation menu
nav:
  - Home: index.md
  - Install: ten-minute-install.md
  - Introduction: introduction.md
  - Pipeline: pipeline.md
  - Hyperparameter Tuning: tuning.md
  - Development: dev.md
  - Contribute: contribute.md
  - Release notes: release_notes.md
  
# Theme
theme:
    features:
      - tabs
      - content.code.copy
      - content.code.annotate
    name: material
    icon:
      logo: material/ninja
    # favicon: material/ninja
    static_templates:
      - 404.html
    palette:
      primary: black

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ubc-provenance/PIDSMaker

copyright: Copyright &copy; 2025 Tristan Bilot
