# ADP@0.611 => https://wandb.ai/tristan_research/framework_framework_tuning_orthrus/sweeps/acrijrsi?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.00001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.4
