# ADP@0.334 => https://wandb.ai/tristan_research/framework_tuning_nodlink/sweeps/lvtogf5e?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 1
  transformation:
    used_methods: none

featurization:
  embed_nodes:
    epochs: 10

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 128
    node_hid_dim: 128
    encoder:
      dropout: 0.4
  