# ADP@0.445 => https://wandb.ai/tristan_research/framework_tuning_threatrace/sweeps/w3n1m03m?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 5

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 64
    encoder:
      dropout: 0.4
