# ADP@0.334 => https://wandb.ai/tristan_research/framework_tuning_sigl/sweeps/evy1rccd?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 5

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.4
