# ADP@0.379 => https://wandb.ai/tristan_research/framework_tuning_amalgame_linear/sweeps/mqoeiewl?nw=nwusertristanbilot

featurization:
  embed_nodes:
    emb_dim: 128

detection:
  gnn_training:
    lr: 0.0001
    node_out_dim: 64
