# ADP@0.172 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/rb2gxxq2?nw=nwusertristanbilot
# In benchmark table: https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/dkapw0ga/workspace?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 10.0

detection:
  gnn_training:
    lr: 0.0001
    node_hid_dim: 128
    encoder:
      dropout: 0.4
  