# ADP@0.334 => https://wandb.ai/tristan_research/framework_tuning_kairos/sweeps/67lqd7nx/workspace

preprocessing:
  build_graphs:
    time_window_size: 10

detection:
  gnn_training:
    lr: 0.00001
    node_hid_dim: 128
    node_out_dim: 128
    encoder:
      dropout: 0.4
