# ADP@0.45 => https://wandb.ai/tristan_research/framework_tuning_rcaid/sweeps/newjk6o0?nw=nwusertristanbilot

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 128
    encoder:
      dropout: 0.4
