#ADP@1 => https://wandb.ai/tristan_research/framework_tuning_kairos/sweeps/whkzho8p/table?nw=nwuserbaoxiang

preprocessing:
  build_graphs:
    time_window_size: 5.0

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 64
    # node_out_dim: -1
    encoder:
      dropout: 0.3