#ADP@1 => https://wandb.ai/tristan_research/framework_tuning_flash/sweeps/bqmgt6xg/table?nw=nwuserbaoxiang

preprocessing:
  build_graphs:
    time_window_size: 5

detection:
  gnn_training:
    lr: 0.001
    node_hid_dim: 64
    encoder:
      dropout: 0.3