# ADP@1.00 => https://wandb.ai/tristan_research/framework_tuning_amalgame_linear/sweeps/42pwlyz1?nw=nwusertristanbilot

preprocessing:
  build_graphs:
    time_window_size: 1.0

featurization:
  embed_nodes:
    emb_dim: 64
    seed: 3

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 256
    encoder:
      dropout: 0.3
