preprocessing:
  build_graphs:
    time_window_size: 1.0

featurization:
  feat_training:
    emb_dim: 64

detection:
  gnn_training:
    lr: 0.001
    node_out_dim: 256
    encoder:
      dropout: 0.3
